version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
    pihole:
      container_name: pihole
      image: pihole/pihole:latest
      network_mode: host
      environment:
        ADMIN_EMAIL: "MY_EMAIL" # Set an administrative contact address for the Block Page
        TZ: 'Europe/Oslo' # Set your timezone to make sure logs rotate at local midnight instead of at UTC midnight.
        WEBPASSWORD: 'PIHOLE_ADMIN_PW' # http://pi.hole/admin password. Run docker logs pihole | grep random to find your random pass.
        PIHOLE_DNS_: '127.0.0.1#53000' # Upstream DNS server(s) for Pi-hole to forward queries to, seperated by a semicolon (supports non-standard ports with #[port number]) e.g 127.0.0.1#5053;8.8.8.8;8.8.4.4
        DNSSEC: 'true' # Enable DNSSEC support
        #DNS_BOGUS_PRIV: 'true' # Enable forwarding of reverse lookups for private ranges
        DNS_FQDN_REQUIRED: 'false' # Never forward non-FQDNs
        #REV_SERVER: 'false' # Enable DNS conditional forwarding for device name resolution
        #REV_SERVER_DOMAIN: '' # If conditional forwarding is enabled, set the domain of the local network router
        #REV_SERVER_TARGET: '' # If conditional forwarding is enabled, set the IP of the local network router
        #REV_SERVER_CIDR: '' # If conditional forwarding is enabled, set the reverse DNS zone (e.g. 192.168.0.0/24)
        ServerIP: 'SERVER_LAN_IP' # --net=host mode requires! Set to your server's LAN IP, used by web block modes and lighttpd bind address
        #ServerIPv6: '' # If you have a v6 network set to your server's LAN IPv6 to block IPv6 ads fully
        VIRTUAL_HOST: 'SERVER_HOSTNAME' # What your web server 'virtual host' is, accessing admin through this Hostname/IP allows you to make changes to the whitelist / blacklists in addition to the default 'http://pi.hole/admin/' address
        #IPv6: 'true' # For unraid compatibility, strips out all the IPv6 configuration from DNS/Web services when false.
        #INTERFACE: '' # The default works fine with our basic example docker run commands. If you're trying to use DHCP with --net host mode then you may have to customize this or DNSMASQ_LISTENING.
        DNSMASQ_LISTENING: 'all' # 'local' listens on all local subnets, 'all' permits listening on internet origin subnets in addition to local, 'single' listens only on the interface specified.
        #WEB_PORT: '' # This will break the 'webpage blocked' functionality of Pi-hole however it may help advanced setups like those running synology or --net=host docker argument. This guide explains how to restore webpage blocked functionality using a linux router DNAT rule: Alternative Synology installation method
        #DNSMASQ_USER: 'root' # Allows running FTLDNS as non-root.
        #TEMPERATUREUNIT: 'c' # Set preferred temperature unit to c: Celsius, k: Kelvin, or f Fahrenheit units.
        #WEBUIBOXEDLAYOUT: 'boxed' # Use boxed layout (helpful when working on large screens)
        #SKIPGRAVITYONBOOT: '' # Use this option to skip updating the Gravity Database when booting up the container. By default this environment variable is not set so the Gravity Database will be updated when the container starts up. Setting this environment variable to 1 (or anything) will cause the Gravity Database to not be updated when container starts up.
        #QUERY_LOGGING: 'true' # Enable query logging or not.
        DHCP_ACTIVE: 'true' # Enable DHCP server. Static DHCP leases can be configured with a custom /etc/dnsmasq.d/04-pihole-static-dhcp.conf
        DHCP_START: 'LAN_DHCP_START' # Start of the range of IP addresses to hand out by the DHCP server (mandatory if DHCP server is enabled).
        DHCP_END: 'LAN_DHCP_END' # End of the range of IP addresses to hand out by the DHCP server (mandatory if DHCP server is enabled).
        DHCP_ROUTER: 'LAN_GATEWAY' # Router (gateway) IP address sent by the DHCP server (mandatory if DHCP server is enabled).
        #DHCP_LEASETIME: '24' # DHCP lease time in hours.
        PIHOLE_DOMAIN: 'LAN_DHCP_DOMAIN' # Domain name sent by the DHCP server.
        #DHCP_IPv6: 'false' # Enable DHCP server IPv6 support (SLAAC + RA).
        #DHCP_rapid_commit: 'false' # Enable DHCPv4 rapid commit (fast address assignment).
      # Volumes store your data between container upgrades
      volumes:
        - './etc-pihole/:/etc/pihole/'
        - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # Recommended but not required (DHCP needs NET_ADMIN)
      # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      cap_add:
        - NET_ADMIN
      restart: unless-stopped
