#!/bin/bash
set -e
#set -x

#######################################
#	Remove docker image and recreate
#
#	Outputs:
#		None
#	Returns:
#		1 upon error
#		0 otherwise
#######################################
function main() {
	local readonly USAGE="Usage: update"

	if [[ "${#}" -ne 0 ]]; then
		err "Error: no argument expected, ${#} received"
		err "${USAGE}"
		return 1
	fi

	if [ "${EUID}" -ne 0 ]; then
		err "Please run as root"
		return 2
	fi

	# Since we're removing the container, we'll have no DNS server
	echo "nameserver 1.1.1.1" > /etc/resolv.conf

	[[ ! -z $(docker ps | grep pihole) ]] && docker stop pihole
	docker rm pihole
	docker-compose up --detach

	# Set DNS back to the pi
	echo "nameserver 127.0.0.1" > /etc/resolv.conf

	return 0
}

main "${@}"; exit
