version: '3.7'

services:
  redis:
    container_name: redis
    image: "redis:alpine"
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    command: redis-server --save "" --appendonly "no"
    env_file:
      - ../common.env
    tmpfs:
      - /var/lib/redis
    restart: unless-stopped

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    env_file:
      - ../common.env
      - ./searxng.env
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
     - 50103:8080
    restart: unless-stopped
