version: '3'

## https://github.com/ajnart/homarr
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    env_file:
      - ../common.env
    volumes:
      - ./config.json:/app/data/configs/default.json
    ports:
      - 80:7575
    restart: unless-stopped
