#!/bin/sh
set -e
set -u
#set -x

main() {
    readonly USAGE="Usage: update container_name"
    [ "$#" -eq 1 ] || { err "Error: one argument expected, ${#} received"; err "$USAGE"; return 1; }
    [ "$(id -u)" -ne 0 ] || { err 'Do NOT run as root'; return 2; }

    readonly container="$(echo "$1" | sed 's/\/$//')"

    # Does the compose-file exist?
    [ -f "$container/docker-compose.yml" ] || { err "Error: docker-compose file '$container/docker-compose.yml' not found", return 3; }
    cd "$container"

	# Since we're removing the container, pihole's DNS server will be down
	[ "$container" = 'pihole' ] \
		&& printf 'nameserver 1.1.1.1\nnameserver 1.0.0.1\n' | sudo tee /etc/resolv.conf >/dev/null

    # Stop
    sudo docker-compose down --rmi local --remove-orphans

    # Update and start
    sudo docker-compose pull
    sudo docker-compose up --detach
    sudo docker system prune prune -f

    # Restore
    [ "$container" = 'pihole' ] \
	    && printf 'nameserver 127.0.0.1\noptions trust-ad\n' | sudo tee /etc/resolv.conf >/dev/null
}

#######################################
#   Print error message to stderr
#   https://google.github.io/styleguide/shellguide.html
#######################################
err() { printf "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*\n" >&2; }

main "$@"; exit
