version: "3"

## https://documentation.portainer.io/v2.0/deploy/ceinstalldocker/
services:
  portainer-ce:
    container_name: portainer-ce
    image: portainer/portainer-ce:latest
    volumes:
      - './portainer_data/:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - 8000:8000
      - 9000:9000
    restart: unless-stopped
