version: "3.9"

## https://github.com/pi-hole/docker-pi-hole/
## https://docs.pi-hole.net/
services:
  unbound:
    container_name: unbound
    image: klutchell/unbound
    hostname: unbound
    networks:
      default:
        ipv4_address: 172.28.0.2
    environment:
      TZ: ${CONFIG_SYSTEM_REGION}
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
    hostname: 'pi.hole'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "50100:80/tcp"
    networks:
      default:
        ipv4_address: 172.28.0.3
    environment:
      ADMIN_EMAIL: "${CONFIG_USER_EMAIL}" # Set an administrative contact address for the Block Page
      TZ: '${CONFIG_SYSTEM_REGION}' # Set your timezone to make sure logs rotate at local midnight instead of at UTC midnight.
      WEBPASSWORD: '${CONFIG_PIHOLE_PW}' # http://pi.hole/admin password. Run docker logs pihole | grep random to find your random pass.
      PIHOLE_DNS_: '172.28.0.2;172.28.0.2' # Upstream DNS server(s) for Pi-hole to forward queries to, seperated by a semicolon (supports non-standard ports with #[port number]) e.g 127.0.0.1#5053;8.8.8.8;8.8.4.4
      #DNSSEC: 'false' # Enable DNSSEC support (Unnecessary when using unbound with dnssec support)
      #DNS_BOGUS_PRIV: 'true' # Enable forwarding of reverse lookups for private ranges
      DNS_FQDN_REQUIRED: 'false' # Never forward non-FQDNs
      REV_SERVER: 'true' # Enable DNS conditional forwarding for device name resolution
      REV_SERVER_DOMAIN: '${CONFIG_DHCP_DOMAIN}' # If conditional forwarding is enabled, set the domain of the local network router
      REV_SERVER_TARGET: ${CONFIG_LAN_IP}'' # If conditional forwarding is enabled, set the IP of the local network router
      REV_SERVER_CIDR: '${CONFIG_DHCP_SUBNET}' # If conditional forwarding is enabled, set the reverse DNS zone (e.g. 192.168.0.0/24)
      #ServerIP: '172.28.0.3' # --net=host mode requires! Set to your server's LAN IP, used by web block modes and lighttpd bind address
      #ServerIPv6: '' # If you have a v6 network set to your server's LAN IPv6 to block IPv6 ads fully
      #VIRTUAL_HOST: '${CONFIG_SERVER_HOSTNAME}' # What your web server 'virtual host' is, accessing admin through this Hostname/IP allows you to make changes to the whitelist / blacklists in addition to the default 'http://pi.hole/admin/' address
      #IPv6: 'true' # For unraid compatibility, strips out all the IPv6 configuration from DNS/Web services when false.
      #INTERFACE: '' # The default works fine with our basic example docker run commands. If you're trying to use DHCP with --net host mode then you may have to customize this or DNSMASQ_LISTENING.
      DNSMASQ_LISTENING: 'all' # 'local' listens on all local subnets, 'all' permits listening on internet origin subnets in addition to local, 'single' listens only on the interface specified.
      #WEB_PORT: '50100' # This will break the 'webpage blocked' functionality of Pi-hole however it may help advanced setups like those running synology or --net=host docker argument. This guide explains how to restore webpage blocked functionality using a linux router DNAT rule: Alternative Synology installation method
      DNSMASQ_USER: 'pihole' # Allows running FTLDNS as non-root.
      #TEMPERATUREUNIT: 'c' # Set preferred temperature unit to c: Celsius, k: Kelvin, or f Fahrenheit units.
      #WEBUIBOXEDLAYOUT: 'boxed' # Use boxed layout (helpful when working on large screens)
      #SKIPGRAVITYONBOOT: '' # Use this option to skip updating the Gravity Database when booting up the container. By default this environment variable is not set so the Gravity Database will be updated when the container starts up. Setting this environment variable to 1 (or anything) will cause the Gravity Database to not be updated when container starts up.
      #QUERY_LOGGING: 'true' # Enable query logging or not.
      #DHCP_ACTIVE: '${CONFIG_PIHOLE_DHCPD}' # Enable DHCP server. Static DHCP leases can be configured with a custom /etc/dnsmasq.d/04-pihole-static-dhcp.conf
      #DHCP_START: '${CONFIG_PIHOLE_DHCP_START}' # Start of the range of IP addresses to hand out by the DHCP server (mandatory if DHCP server is enabled).
      #DHCP_END: '${CONFIG_PIHOLE_DHCP_END}' # End of the range of IP addresses to hand out by the DHCP server (mandatory if DHCP server is enabled).
      #DHCP_ROUTER: '${CONFIG_LAN_GATEWAY}' # Router (gateway) IP address sent by the DHCP server (mandatory if DHCP server is enabled).
      #DHCP_LEASETIME: '24' # DHCP lease time in hours.
      #PIHOLE_DOMAIN: '${CONFIG_USER_DOMAIN}' # Domain name sent by the DHCP server.
      #DHCP_IPv6: 'false' # Enable DHCP server IPv6 support (SLAAC + RA).
      #DHCP_rapid_commit: 'false' # Enable DHCPv4 rapid commit (fast address assignment).
      # Volumes store your data between container upgrades
    # Recommended but not required (DHCP needs NET_ADMIN)
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN
    depends_on:
      - unbound
    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.0.0/24
        gateway: 172.28.0.1
