version: "3.9"

## https://github.com/pi-hole/docker-pi-hole/
## https://docs.pi-hole.net/
services:
  unbound:
    container_name: unbound
    image: klutchell/unbound
    hostname: unbound
    networks:
      default:
        ipv4_address: 172.28.0.2
    env_file:
      - ../common.env
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
    hostname: 'pi.hole'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "50100:80/tcp"
    networks:
      default:
        ipv4_address: 172.28.0.3
    env_file:
      - ../common.env
      - ./pihole.env
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    depends_on:
      - unbound
    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      config:
      - subnet: 172.28.0.0/24
        gateway: 172.28.0.1
