version: "3"

## https://hub.docker.com/r/tzahi12345/youtubedl-material
services:
  ytdl-mongo-db:
    container_name: ytdl-mongo-db
    image: mongo:4.4.14 # >= 5 do not work on pi4b yet
    env_file:
      - ../common.env
    volumes:
      - ./db/:/data/db
    restart: unless-stopped
  ytdl-material:
    container_name: ytdl-material
    image: tzahi12345/youtubedl-material:nightly
    env_file:
      - ../common.env
      - ./ytdl-material.env
    depends_on:
      - ytdl-mongo-db
    volumes:
      - ./app/appdata:/app/appdata
      - ./app/audio:/app/audio
      - ./app/video:/app/video
      - ./app/subscriptions:/app/subscriptions
      - ./app/users:/app/users
    ports:
      - 50101:17442
    restart: unless-stopped
