version: "2.1"

## https://hub.docker.com/r/linuxserver/code-server
services:
  code-server:
    container_name: code-server
    image: ghcr.io/linuxserver/code-server
    environment:
      - PUID=CONFIG_USER_UID
      - PGID=CONFIG_USER_GID
      - TZ=Europe/Oslo
      - PASSWORD=CONFIG_CODESERVER_PASSWORD #optional
#      - HASHED_PASSWORD= #optional
#      - SUDO_PASSWORD=password #optional
#      - SUDO_PASSWORD_HASH= #optional
#      - PROXY_DOMAIN=code-server.my.domain #optional
#      - UMASK=
    volumes:
      - './etc-codeserver/:/config'
    ports:
      - 8443:8443
    restart: unless-stopped