version: "3"

## https://hub.docker.com/r/linuxserver/code-server
services:
  code-server:
    container_name: code-server
    image: lscr.io/linuxserver/code-server:latest
    env_file:
      - ../common.env
      - ./code-server.env
    volumes:
      - './workspace/:/config/workspace'
    ports:
      - 50104:8443
    restart: unless-stopped
