version: "3"

## https://github.com/louislam/uptime-kuma
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    env_file:
      - ../common.env
    volumes:
      - './etc-uptimekuma/:/app/data'
    ports:
      - 50102:3001
    restart: unless-stopped
