version: "2.1"

## https://hub.docker.com/r/linuxserver/duckdns/
services:
  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns
    environment:
      PUID: ${CONFIG_USER_UID}
      PGID: ${CONFIG_USER_GID}
      TZ: Europe/Oslo
      SUBDOMAINS: ${CONFIG_DUCKDNS_USERNAME}
      TOKEN: ${CONFIG_DUCKDNS_TOKEN}
      LOG_FILE: 'true' #optional
    volumes:
      - './etc-duckdns/:/config'
    restart: unless-stopped
