version: "3"

## https://hub.docker.com/r/linuxserver/duckdns/
services:
  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns:latest
    env_file:
      - ../common.env
      - ./duckdns.env
    volumes:
      - './duck.log:/config/duck.log'
    restart: unless-stopped
